import type { Post } from './types'

export const externalPosts: Post[] = [
  {
    title: 'How we made v0 an effective coding agent',
    description: 'Learn how we built v0 to be an effective AI coding agent through careful system design and iteration.',
    body: '',
    date: '2026-01-07T10:00:00.000Z',
    slug: '',
    tags: [],
    lastModified: 0,
    isThirdParty: true,
    href: 'https://vercel.com/blog/how-we-made-v0-an-effective-coding-agent',
    type: 'post',
  },
  {
    title: 'Introducing the v0 composite model family',
    description: 'Introducing the v0 composite model family.',
    body: '',
    date: '2025-06-01T10:00:00.000Z',
    slug: '',
    tags: [],
    lastModified: 0,
    isThirdParty: true,
    href: 'https://vercel.com/blog/v0-composite-model-family',
    type: 'post',
  },
  {
    title: 'Introducing AI SDK 3.0 with Generative UI support',
    description:
      'Stream React Components from LLMs to deliver richer user experiences.',
    body: '',
    date: '2024-03-01T10:00:00.000Z',
    slug: '',
    tags: [],
    lastModified: 0,
    isThirdParty: true,
    href: 'https://vercel.com/blog/ai-sdk-3-generative-ui',
    type: 'post',
  },
  {
    title: 'Introducing the Vercel AI SDK',
    description:
      'An interoperable, streaming-enabled, edge-ready software development kit for AI apps built with React and Svelte.',
    body: '',
    date: '2023-06-15T13:00:00.000Z',
    slug: '',
    tags: [],
    lastModified: 0,
    isThirdParty: true,
    href: 'https://vercel.com/blog/introducing-the-vercel-ai-sdk',
    type: 'post',
  },
  {
    title: 'Improving the accessibility of our Next.js site',
    description:
      "We've made some improvements to the accessibility of our Next.js site. Here's how we did it.",
    body: '',
    date: '2022-09-30T13:00:00.000Z',
    slug: '',
    tags: [],
    lastModified: 0,
    isThirdParty: true,
    href: 'https://vercel.com/blog/improving-the-accessibility-of-our-nextjs-site',
    type: 'post',
  },
  {
    title: 'New edge dev infrastructure',
    description: 'New edge dev infrastructure.',
    body: '',
    date: '2020-07-21T10:00:00.000Z',
    slug: '',
    tags: [],
    lastModified: 0,
    isThirdParty: true,
    href: 'https://vercel.com/blog/new-edge-dev-infrastructure',
    type: 'post',
  },
]