import React, { type ReactNode } from 'react'
import { diffLines } from 'diff'
import Link from '@components/link'
import Info from '@components/icons/info'
import Home from '@components/icons/home'
import { MDXNote } from './components/mdx-note'
import { createIslandComponents } from './island-components'
import { Img } from '../../framework/images'
import type { TweetMap } from '../../framework/tweets'
import type { DimensionMap } from '../../framework/image-dims'
// Deep import on purpose; see the note on makeTweet below.
import { EmbeddedTweet } from '../../node_modules/react-tweet/dist/twitter-theme/embedded-tweet.js'
