/**
 * Regenerates `app/styles/fragments/react-tweet.css`.
 *
 * react-tweet ships its styling as ~20 CSS modules plus a `theme.css` of custom
 * properties. The build has no CSS-module compiler any more -- every other
 * stylesheet in this repo is written with its scoping already in the class name
 * -- so this script does that scoping once, ahead of time, and commits the
 * result. `.foo` in `tweet-header.module.css` becomes `.rt-header-foo`, and the
 * build's `react-tweet` esbuild plugin hands the components the same names.
 *
 * Only the modules `EmbeddedTweet` actually reaches are emitted, which is why
 * this bundles rather than globbing: the skeleton and not-found cards are dead
 * weight here. Rendering is entirely build-time, so nothing about this ships as
 * JavaScript.
 *
 * Run it when the react-tweet version in package.json changes:
 *   bun run scripts/react-tweet-css.ts
 */
import fs from 'node:fs/promises'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as esbuild from 'esbuild'

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const OUT = path.join(ROOT, 'app', 'styles', 'fragments', 'react-tweet.css')

const require_ = createRequire(path.join(ROOT, 'package.json'))

/**
 * `theme.css` is a declared export; the per-component modules are not, which is
 * why `static-components.tsx` deep-imports through `node_modules/` too. Every
 * path here is derived from the one specifier the package does export.
 */
const THEME = require_.resolve('react-tweet/theme.css')
const PKG = path.dirname(path.dirname(path.dirname(THEME)))

/**
 * The class-name prefix for one module, from its filename: `tweet-header` ->
 * `header`, `quoted-tweet-body` -> `quoted-body`. Local names collide across
 * files -- five modules export a `.root` -- so the prefix has to carry the
 * file, which is exactly what CSS-module scoping was doing with a hash.
 */
export function prefixFor(file: string): string {
  const stem = path.basename(file).replace(/\.module\.css$/, '')
  return `rt-${stem.replace(/^quoted-tweet-/, 'quoted-').replace(/^tweet-/, '')}-`
}

/**
 * Rewrites every class selector in a CSS module to its scoped name.
 *
 * A class selector is a `.` that follows something other than a word character,
 * a dot or a hyphen, which is what keeps `0.75rem` and `rgb(0 0 0 / 3%)` out of
 * it. Sound for these files specifically: they use no `composes`, no `:global`,
 * no `url()`, no `content:` string and no `@keyframes`, all asserted below.
 */
export function scopeClasses(css: string, prefix: string): string {
  return css.replace(
    /(^|[^\w.-])\.([_a-zA-Z][\w-]*)/g,
    (_, before: string, name: string) => `${before}.${prefix}${name}`,
  )
}

function assertMechanical(file: string, css: string): void {
  for (const banned of ['composes', ':global', ':local', 'url(']) {
    if (css.includes(banned)) {
      throw new Error(`${file}: ${banned} needs a hand-written rule, not this`)
    }
  }
  // The property, not `justify-content`. A `content` string could hold a `.`.
  if (/(?:^|[^\w-])content\s*:/.test(css)) {
    throw new Error(`${file}: a content string may hide a class-like literal`)
  }
  if (/@keyframes/.test(css)) {
    throw new Error(`${file}: @keyframes names are scoped too; handle by hand`)
  }
}

/** The modules `EmbeddedTweet` pulls in, in a stable order. */
async function reachableModules(): Promise<string[]> {
  const entry = path.join(PKG, 'dist', 'twitter-theme', 'embedded-tweet.js')
  const found = new Set<string>()
  await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    write: false,
    platform: 'node',
    format: 'esm',
    logLevel: 'silent',
    loader: { '.js': 'jsx' },
    plugins: [
      {
        name: 'collect-css-modules',
        setup(build) {
          build.onLoad({ filter: /\.module\.css$/ }, (args) => {
            found.add(args.path)
            return { contents: 'export default {}', loader: 'js' }
          })
          // `tweet-container.js` imports theme.css for its side effect.
          build.onLoad({ filter: /\.css$/ }, () => ({
            contents: 'export default {}',
            loader: 'js',
          }))
        },
      },
    ],
  })
  return [...found].sort((a, b) => a.localeCompare(b))
}

const modules = await reachableModules()
const theme = await fs.readFile(THEME, 'utf8')

const { version } = JSON.parse(
  await fs.readFile(path.join(PKG, 'package.json'), 'utf8'),
) as { version: string }

const parts = [
  `/* Generated by scripts/react-tweet-css.ts from react-tweet ${version}.\n` +
    `   Do not edit by hand. ${modules.length} modules, theme.css first, each\n` +
    `   module's classes scoped as .rt-<module>-<class>. */`,
  theme.trim(),
]

for (const file of modules) {
  const css = await fs.readFile(file, 'utf8')
  assertMechanical(file, css)
  const short = file.slice(
    file.lastIndexOf('react-tweet/') + 'react-tweet/'.length,
  )
  parts.push(`/* ${short} */`, scopeClasses(css, prefixFor(file)).trim())
}

await fs.writeFile(OUT, `${parts.join('\n\n')}\n`)
console.log(
  `${path.relative(ROOT, OUT)}: ${modules.length} modules + theme, ${(await fs.stat(OUT)).size} bytes`,
)
